name: Maven Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the project
        run: mvn -B package --file course_work2.iml

      - name: Upload Artefact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: "*.exe"
          retention-days: 5
  
  telergam:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artefact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: my-artifact
      
      - name: failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            You failed
      
      - name: send mess
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: my-artifact/**
          message: |
            ${{ github.actor }} created commit № ${{ github.run_number }}:
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            Download ${{ env.app_name }} Artifacts
