name: Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build the project
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging

      - name: Set up a cache for maven
        uses: actions/cache@v2
        with:
          path: ~./m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          retore-keys: ${{ runner.os }}-m2
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: staging
          retention-days: 5
  
  telergam:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: my-artifact
      
      - name: Failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} have failed to commit in repository: ${{ github.repository }}
      
      - name: Success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: my-artifact/**
          message: |
            Repository: ${{ github.repository }} 
            
            ${{ github.actor }} created an event: ${{ github.event_name }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            Download Artifacts: ${{ env.app_name }} 
